BATCH_SIZE: 128
EARLY_STOPPING: 6400

SAVE_PLOT: False
SAVE_MODEL: True
CUDA_ENABLED: True
NOISE: False
NUM_DATA: 5000 

MODEL_DIR: ''
MODEL_NAME: 'path_to_dataset'
TRAIN_MODE: 'nn'

num_layers: 8
neurons_per_layer: 40
alpha: 1
collocation_multiplier: 4